"""mudando o nome da coluna data_created para data_criacao.

Revision ID: 0957b8bc7dd6
Revises: 2e597e45f6f6
Create Date: 2026-01-19 15:05:25.933607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0957b8bc7dd6'
down_revision = '2e597e45f6f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.Date(), nullable=True))
        batch_op.drop_column('data_upload')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_upload', sa.DATE(), nullable=True))
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
