"""add coluna de data de atualização para exibir quando foi a ultima atualização do registro.

Revision ID: 1bb09df2e76f
Revises: 7e9fa446ab7c
Create Date: 2026-01-23 10:15:28.858150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bb09df2e76f'
down_revision = '7e9fa446ab7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_atualizacao', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.drop_column('data_atualizacao')

    # ### end Alembic commands ###
