"""modificação: colunas em null.

Revision ID: 1e38b3d806d0
Revises: ce17d2c55052
Create Date: 2026-01-12 11:35:55.238805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e38b3d806d0'
down_revision = 'ce17d2c55052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.alter_column('data_encerramento',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('tempo_coletar',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('desfecho',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.alter_column('desfecho',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('tempo_coletar',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('data_encerramento',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
