"""add coluna de data_created no registry_model.

Revision ID: 2e597e45f6f6
Revises: 1e38b3d806d0
Create Date: 2026-01-19 14:58:06.738663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e597e45f6f6'
down_revision = '1e38b3d806d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_upload', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.drop_column('data_upload')

    # ### end Alembic commands ###
