"""ALTER: LINE DO MODEL REGISTRY.

Revision ID: 36dff15e5d53
Revises: 5c116872e743
Create Date: 2026-03-27 11:25:51.185403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36dff15e5d53'
down_revision = '5c116872e743'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linezolid', sa.String(length=50), nullable=True))
        batch_op.drop_column('linezolida')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linezolida', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('linezolid')

    # ### end Alembic commands ###
