"""add nazol column field.

Revision ID: 44872e38993d
Revises: 1bb09df2e76f
Create Date: 2026-01-28 09:47:01.871946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44872e38993d'
down_revision = '1bb09df2e76f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nazol', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.drop_column('nazol')

    # ### end Alembic commands ###
