"""novas colunas colocando na table registros.

Revision ID: 541d140cb2f6
Revises: 0957b8bc7dd6
Create Date: 2026-01-21 14:51:47.582278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '541d140cb2f6'
down_revision = '0957b8bc7dd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notificacao', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('dialise', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('material_coletada', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('microorganismo', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('local', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amicacina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ampicilina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amoxicilina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amoxicilina_clavulanato', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amp_sulbactam', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('azitromicina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cefalexina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cefazolina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cefepime', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ceftazidime', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cefoxitina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ceftriaxone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cefuroxime', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ciprofloxacino', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('clindamicina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('daptomicina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('eritromicina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ertapenem', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gentamicina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('imipenem', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('levofloxacino', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('linezolida', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('moxifloxacina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('oxacilina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ofloxacina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('penicilina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meropenem', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('minociclina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('norfloxacina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('piperacilina_tazobactam', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('polimixina_b', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rifampicina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('streptomicina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('trimetoprim_sulfametoxazol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('teicoplanina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tetraciclina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tigeciclina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('vancomicina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('anfotericina_b', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fluconazol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ketoconazol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('voriconazol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nitrofurantoina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('aztreonam', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cloranfenicol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('colistina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ceftazidima_avibactam', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ceftolozano_tazobactam', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ceftarolina', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('cefotaxime', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ceftibufen', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('observacao', sa.String(length=255), nullable=True))
        batch_op.alter_column('diagnostico',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.alter_column('diagnostico',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('observacao')
        batch_op.drop_column('ceftibufen')
        batch_op.drop_column('cefotaxime')
        batch_op.drop_column('ceftarolina')
        batch_op.drop_column('ceftolozano_tazobactam')
        batch_op.drop_column('ceftazidima_avibactam')
        batch_op.drop_column('colistina')
        batch_op.drop_column('cloranfenicol')
        batch_op.drop_column('aztreonam')
        batch_op.drop_column('nitrofurantoina')
        batch_op.drop_column('voriconazol')
        batch_op.drop_column('ketoconazol')
        batch_op.drop_column('fluconazol')
        batch_op.drop_column('anfotericina_b')
        batch_op.drop_column('vancomicina')
        batch_op.drop_column('tigeciclina')
        batch_op.drop_column('tetraciclina')
        batch_op.drop_column('teicoplanina')
        batch_op.drop_column('trimetoprim_sulfametoxazol')
        batch_op.drop_column('streptomicina')
        batch_op.drop_column('rifampicina')
        batch_op.drop_column('polimixina_b')
        batch_op.drop_column('piperacilina_tazobactam')
        batch_op.drop_column('norfloxacina')
        batch_op.drop_column('minociclina')
        batch_op.drop_column('meropenem')
        batch_op.drop_column('penicilina')
        batch_op.drop_column('ofloxacina')
        batch_op.drop_column('oxacilina')
        batch_op.drop_column('moxifloxacina')
        batch_op.drop_column('linezolida')
        batch_op.drop_column('levofloxacino')
        batch_op.drop_column('imipenem')
        batch_op.drop_column('gentamicina')
        batch_op.drop_column('ertapenem')
        batch_op.drop_column('eritromicina')
        batch_op.drop_column('daptomicina')
        batch_op.drop_column('clindamicina')
        batch_op.drop_column('ciprofloxacino')
        batch_op.drop_column('cefuroxime')
        batch_op.drop_column('ceftriaxone')
        batch_op.drop_column('cefoxitina')
        batch_op.drop_column('ceftazidime')
        batch_op.drop_column('cefepime')
        batch_op.drop_column('cefazolina')
        batch_op.drop_column('cefalexina')
        batch_op.drop_column('azitromicina')
        batch_op.drop_column('amp_sulbactam')
        batch_op.drop_column('amoxicilina_clavulanato')
        batch_op.drop_column('amoxicilina')
        batch_op.drop_column('ampicilina')
        batch_op.drop_column('amicacina')
        batch_op.drop_column('local')
        batch_op.drop_column('microorganismo')
        batch_op.drop_column('material_coletada')
        batch_op.drop_column('dialise')
        batch_op.drop_column('notificacao')

    # ### end Alembic commands ###
