"""create table registry.

Revision ID: ce17d2c55052
Revises: 8373edd9aeb3
Create Date: 2026-01-12 09:29:55.935481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce17d2c55052'
down_revision = '8373edd9aeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_paciente', sa.String(length=255), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('data_da_coleta', sa.Date(), nullable=False),
    sa.Column('data_encerramento', sa.Date(), nullable=False),
    sa.Column('tempo_coletar', sa.Integer(), nullable=False),
    sa.Column('diagnostico', sa.String(length=255), nullable=False),
    sa.Column('desfecho', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros')
    # ### end Alembic commands ###
