"""alterando as datas para nullable igual a True.

Revision ID: f0d04c440c82
Revises: 541d140cb2f6
Create Date: 2026-01-21 15:51:05.051750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d04c440c82'
down_revision = '541d140cb2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.alter_column('data_admissao',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('data_da_coleta',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros', schema=None) as batch_op:
        batch_op.alter_column('data_da_coleta',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('data_admissao',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
